services:
  - type: web
    name: render-node-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webnodejs
          property: connectionString
